### ISSUE TITLE
Keep events on same line, connect multiday events.

### ISSUE THREAD

**Issue by sirtet** [fabrixxm/Year-View#12]
This plugin woud be awesome, but i can't really use it, since it's too hard to get an overview.

There are 2 problems for me:
A smaller one is, that multiday-events are not connected, so they look the same as several single-day events.

But the real showstopper is, that a multiday event can get spread over multiple rows, which makes it even harder to identify, unless you click it, as i did in the middle-month, day 14 to 17 of the screenshot.
![image](https://cloud.githubusercontent.com/assets/3509308/4990012/030209a2-6982-11e4-851c-f23c0930d6e5.png)

**Comment by tetefolle** [comment]
+1

**Comment by fabrixxm** [comment]
With commit b543526 I'm trying to do this. It's not perfect and is not fast. And it's not yet released..

<img width="180" alt="schermata 2018-04-11 alle 15 02 35" src="https://user-images.githubusercontent.com/309361/38618272-65bf138e-3d99-11e8-8c64-6465527df60e.png">

**Comment by fabrixxm** [comment]
released in v0.6.0 . Not yet optimal
