### ISSUE TITLE
enhancement: add a print layout for a year view

### ISSUE THREAD

**Issue by SimonHeimberg** [fabrixxm/Year-View#16]
I would like the functionality to print the year view. 

---

The following files in lightning directory have something to do with the current 3 choices.
 calendar-js/calMonthGridPrinter.js
 calendar-js/calWeekGridPrinter.js 
 calendar-js/calListFormatter.js

I do not know where to put a modified copy of this files, else I could do some tries.

**Comment by fabrixxm** [comment]
There was a printing layout. Then Lightning changed how printing worked and I don't remember the details but adding back the functionality was too much work :-)

**Comment by fabrixxm** [comment]
last version adds a simple yearly "busy/free" print option
