### ISSUE TITLE
Year-View doesn't integrate in Lightbird

### ISSUE THREAD

**Issue by MuellerSeb** [fabrixxm/Year-View#20]
I am running Thunderbird 52.7 on Ubuntu 16.04 with Lightning 5.4 and Lightbird 0.7.1.
I was using the Year View Addon, which worked like a charm in Thunderbird, but it doesn't integrate in Lightbird.

Is there a way to make that possible?

Apart from that: Great work!

PS: I also created an issue (https://github.com/Exalm/lightbird/issues/42) on Lightbird, because I don't know where the problem really is located.

**Comment by fabrixxm** [comment]
Seamonkey is not supported anymore (until Lightning 6 is ported to it).
