### ISSUE TITLE
Support Thunderbird 68

### ISSUE THREAD

**Issue by fabrixxm** [fabrixxm/Year-View#28]
looks like there are major changes in TB68 ( https://developer.thunderbird.net/add-ons/updates )
As this addon is mostly an extract from Lightning, I have to see what Lightning is doing but:

- not before TB68 is out stable
- not if it will require a full rewrite: in this case this addon will be discontinued

**Comment by gdsotirov** [comment]
Have you already looked at recently released TB68?

**Comment by fabrixxm** [comment]
not yet
